### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by jamesmayfield** [iscoe/dragonfly#47]
I searched for a string (ପାଟନା) then clicked on one of the resulting links, and got this:

127.0.0.1 - - [16/Jul/2019 23:25:00] INFO: Saving annotations for IL11_NW_020884_20150525_J00410O4L.conll.txt
127.0.0.1 - - [16/Jul/2019 23:25:00] "POST /save HTTP/1.1" 200 -
127.0.0.1 - - [16/Jul/2019 23:25:00] "POST /save HTTP/1.1" 200 -
127.0.0.1 - - [16/Jul/2019 23:25:00] "GET /IL11_NW_021146_20160921_J00410QQL.conll.txt HTTP/1.1" 500 -
127.0.0.1 - - [16/Jul/2019 23:25:00] "GET /IL11_NW_021146_20160921_J00410QQL.conll.txt HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mayfield/Documents/Projects/dragonfly/dragonfly/views.py", line 48, in view
    content = dr.render(app, filename, file_index)
  File "/Users/mayfield/Documents/Projects/dragonfly/dragonfly/renderer.py", line 96, in render
    row.set_suggestions([freqs.get_percentage(x) for x in row.strings])
  File "/Users/mayfield/Documents/Projects/dragonfly/dragonfly/renderer.py", line 96, in <listcomp>
    row.set_suggestions([freqs.get_percentage(x) for x in row.strings])
  File "/Users/mayfield/Documents/Projects/dragonfly/dragonfly/recommend.py", line 258, in get_percentage
    return self.corpus_data.tagged_counts[word] / self.corpus_data.counts[word]
ZeroDivisionError: division by zero
127.0.0.1 - - [16/Jul/2019 23:25:00] "GET /IL11_NW_021146_20160921_J00410QQL.conll.txt?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -

**Comment by cash** [comment]
I thought I fixed that before I left tonight. Have you pulled recently?

**Comment by jamesmayfield** [comment]
I blew away all the .dragonfly files, restarted everything, and finally got it working again. But apparently there was a pull I missed, so maybe that will help prevent it from happening again.
